PUSH_SIGNAL_IMAGE_VERSION="1.0.0-RC1"
PULL_SIGNAL_IMAGE_VERSION="1.0.0-RC1"
SIGNAL_PERSISTER_IMAGE_VERSION="1.0.0-RC1"
AGREEMENT_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC1"
ESERVICE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC1"
PURPOSE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC1"
LOAD_TESTING_IMAGE_VERSION="1.0.0-RC1"

JOB_BATCH_CLEANUP_IMAGE_VERSION="1.0.0-RC1"
