PUSH_SIGNAL_IMAGE_VERSION="1.0.0-RC2"
PULL_SIGNAL_IMAGE_VERSION="1.0.0-RC2"
SIGNAL_PERSISTER_IMAGE_VERSION="1.0.0-RC2"
AGREEMENT_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC2"
ESERVICE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC2"
PURPOSE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC2"
LOAD_TESTING_IMAGE_VERSION="1.0.0-RC2"

JOB_BATCH_CLEANUP_IMAGE_VERSION="1.0.0-RC2"
