PUSH_SIGNAL_IMAGE_VERSION="1.0.0-RC3"
PULL_SIGNAL_IMAGE_VERSION="1.0.0-RC3"
SIGNAL_PERSISTER_IMAGE_VERSION="1.0.0-RC3"
AGREEMENT_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC3"
ESERVICE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC3"
PURPOSE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC3"
LOAD_TESTING_IMAGE_VERSION="1.0.0-RC3"

JOB_BATCH_CLEANUP_IMAGE_VERSION="1.0.0-RC3"
