apiVersion: v1
kind: ConfigMap
metadata:
  name: common-signal-store
  namespace: vapt
data:
  DB_HOST_RW: "signalhub-signal-store-vapt.cluster-cbm0gi8ysy9g.eu-south-1.rds.amazonaws.com"
  DB_HOST_RO: "signalhub-signal-store-vapt.cluster-ro-cbm0gi8ysy9g.eu-south-1.rds.amazonaws.com"
  DB_NAME: "signal_store"
  DB_PORT: "5432"
  DB_SIGNALHUB_SCHEMA: "VAPT_SIGNALHUB"
  DB_INTEROP_SCHEMA: "VAPT_INTEROP"
  DB_USE_SSL: "true"
