repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
      # TODO: issue when validating modules
      # - id: terraform_validate
      #   args:
      #     - --init-args=-lockfile=readonly
      #     - --args=-json
      #     - --args=-no-color
