name: "signalhub-be-signal-persister"

roleArn: "arn:aws:iam::058264553932:role/signalhub-be-signal-persister-dev"

service:
  create: false
  
configmap:
  QUEUE_URL: "https://sqs.eu-south-1.amazonaws.com/058264553932/signalhub-push-signal-dev"

deployment:
  envFromConfigmaps:
    SH_DB_HOST: "common-signal-store.SH_DB_HOST"
    SH_DB_NAME: "common-signal-store.SH_DB_NAME"
    SH_DB_PORT: "common-signal-store.SH_DB_PORT"
    SH_DB_SCHEMA: "common-signal-store.SH_DB_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.SH_DB_USE_SSL"
  envFromSecrets:
    SH_DB_USERNAME: "signal-store-signal-persister-user.username"
    SH_DB_PASSWORD: "signal-store-signal-persister-user.password"
  livenessProbe:
  readinessProbe:
