name: "signalhub-be-signal-persister"

roleArn: "arn:aws:iam::058264553932:role/signalhub-be-signal-persister-dev"

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

configmap:
  QUEUE_URL: "https://sqs.eu-south-1.amazonaws.com/058264553932/signalhub-push-signal-dev"
  SH_MAX_CONNECTION_POOL: "10"

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "common-flyway-migrations"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      FLYWAY_SCHEMAS: "dev_interop,dev_signalhub"
    envFromConfigmaps:
      POSTGRES_HOST: "common-signal-store.DB_HOST_RW"
      POSTGRES_PORT: "common-signal-store.DB_PORT"
      POSTGRES_DB: "common-signal-store.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "signal-store-flyway-user.username"
      FLYWAY_PASSWORD: "signal-store-flyway-user.password"

  envFromConfigmaps:
    SH_DB_HOST: "common-signal-store.DB_HOST_RW"
    SH_DB_NAME: "common-signal-store.DB_NAME"
    SH_DB_PORT: "common-signal-store.DB_PORT"
    SH_DB_SIGNALHUB_SCHEMA: "common-signal-store.DB_SIGNALHUB_SCHEMA"
    SH_DB_INTEROP_SCHEMA: "common-signal-store.DB_INTEROP_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.DB_USE_SSL"
  envFromSecrets:
    SH_DB_USERNAME: "signal-store-signal-persister-user.username"
    SH_DB_PASSWORD: "signal-store-signal-persister-user.password"
  livenessProbe:
  readinessProbe:
