name: "signalhub-be-pull-signal"

roleArn: "arn:aws:iam::058264553932:role/signalhub-be-pull-signal-dev"

service:
  create: true
  portName: http
  containerPort: 8088
  targetGroupArn: "arn:aws:elasticloadbalancing:eu-south-1:058264553932:targetgroup/dev-pull-signal/e4ba4fd60b328edd"

configmap:
  ACCEPTED_AUDIENCE: "interop-signalhub-pull-signal"
  QUEUE_URL: "https://sqs.eu-south-1.amazonaws.com/058264553932/signalhub-push-signal-dev"
  KEY_ID: "0jsvLoiKfoL5p5LuovKFgsB945eHsocHkrtt5-P0cYY"
  KMS_KEY_ID: "2139e931-fe83-45ee-94a8-cf8fe5b494f1"
  SUBJECT: "725ae6e6-8ae0-41d4-bceb-d995a74356ef"
  ISSUER: "725ae6e6-8ae0-41d4-bceb-d995a74356ef"
  AUDIENCE: "auth.dev.interop.pagopa.it/client-assertion"
  PURPOSE_ID: "b693eb6e-73dd-4b58-a42a-3e064a6a4cab"
  URL_AUTH_TOKEN: "https://auth.dev.interop.pagopa.it/token.oauth2"
  CLIENT_ID: "725ae6e6-8ae0-41d4-bceb-d995a74356ef"
  GRANT_TYPE: "client_credentials"
  ASSERTION_TYPE: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
  EXPIRES_IN_SEC: "3600"
  GATEWAY_URL: "https://api.dev.interop.pagopa.it/0.0"

deployment:
  env:
    HOST: "0.0.0.0"
    PORT: 8088
  envFromConfigmaps:
    WELL_KNOWN_URLS: "common-jwt.WELL_KNOWN_URLS"
    SH_DB_HOST: "common-signal-store.SH_DB_HOST"
    SH_DB_NAME: "common-signal-store.SH_DB_NAME"
    SH_DB_PORT: "common-signal-store.SH_DB_PORT"
    SH_DB_SCHEMA: "common-signal-store.SH_DB_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.SH_DB_USE_SSL"
  envFromSecrets:
    SH_DB_USERNAME: "signal-store-pull-signal-user.username"
    SH_DB_PASSWORD: "signal-store-pull-signal-user.password"
  livenessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
  readinessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
