name: "signalhub-be-pull-signal"

serviceAccount:
  roleArn: "arn:aws:iam::058264553932:role/signalhub-be-pull-signal-dev"

service:
  create: true
  portName: http
  containerPort: 8088
  targetGroupArn: "arn:aws:elasticloadbalancing:eu-south-1:058264553932:targetgroup/dev-pull-signal/e4ba4fd60b328edd"

configmap:
  ACCEPTED_AUDIENCE: "dev.interop.pagopa.it/m2m"
  API_VERSION: "1.0"
  RATE_LIMITER_MAX_REQUESTS: "50"
  RATE_LIMITER_RATE_INTERVAL_MILLIS: "1000"
  RATE_LIMITER_BURST_PERCENTAGE: "1"
  RATE_LIMITER_TIMEOUT_MILLIS: "500"
  FEATURE_FLAG_SIGNALHUB_WHITELIST: "true"
  # PUT IN WHITELIST EVENT THE ORGANIZATION NEEDED BY QA TEST
  SIGNALHUB_WHITELIST: "e79a24cd-8edc-441e-ae8d-e87c3aea0059,69e2865e-65ab-4e48-a638-2037a9ee2ee7,05937ccb-951e-47e4-b48e-e9dcaf053097"

deployment:
  env:
    HOST: "0.0.0.0"
    PORT: 8088
    SH_MAX_CONNECTION_POOL: "10"
  envFromConfigmaps:
    WELL_KNOWN_URLS: "common-jwt.WELL_KNOWN_URLS"
    SH_DB_HOST: "common-signal-store.DB_HOST_RO"
    SH_DB_NAME: "common-signal-store.DB_NAME"
    SH_DB_PORT: "common-signal-store.DB_PORT"
    SH_DB_SIGNALHUB_SCHEMA: "common-signal-store.DB_SIGNALHUB_SCHEMA"
    SH_DB_INTEROP_SCHEMA: "common-signal-store.DB_INTEROP_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.DB_USE_SSL"
    RATE_LIMITER_REDIS_HOST: common-redis.RL_HOST
    RATE_LIMITER_REDIS_PORT: common-redis.RL_PORT
  envFromSecrets:
    SH_DB_USERNAME: "signal-store-pull-signal-user.username"
    SH_DB_PASSWORD: "signal-store-pull-signal-user.password"
  livenessProbe:
    httpGet:
      path: "/health"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
  readinessProbe:
    httpGet:
      path: "/health"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
