namespace: "prod"
techStack: "nodejs"

deployment:
  replicas: 1
  image:
    repositoryPrefix: "CHANGE-THIS.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  resources:
    requests:
      cpu: "1"
      memory: "2Gi" # CHECK THIS!
    limits:
      cpu: "1"
      memory: "2Gi" # CHECK THIS!
  env:
    LOG_LEVEL: "info"
