name: "signalhub-be-eservice-event-consumer"

roleArn: "arn:aws:iam::058264553932:role/signalhub-be-eservice-event-consumer-dev"

service:
  create: false

configmap:
  KAFKA_GROUP_ID: "signalhub-dev-eservice-event-consumer"

deployment:
  envFromConfigmaps:
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    KAFKA_TOPIC: "common-kafka.ESERVICE_TOPIC"
    SH_DB_HOST: "common-signal-store.SH_DB_HOST"
    SH_DB_NAME: "common-signal-store.SH_DB_NAME"
    SH_DB_PORT: "common-signal-store.SH_DB_PORT"
    SH_DB_SCHEMA: "common-signal-store.SH_DB_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.SH_DB_USE_SSL"
  envFromFieldRef:
    KAFKA_CLIENT_ID: "metadata.name"
  envFromSecrets:   
    SH_DB_USERNAME: "signal-store-eservice-consumer-user.username"
    SH_DB_PASSWORD: "signal-store-eservice-consumer-user.password"
