name: "signalhub-be-batch-cleanup"

techStack: "nodejs"

schedule: "30 * * * *"

concurrencyPolicy: "Forbid"
activeDeadlineSeconds: null

configmap:
  SIGNALS_RETENTION_HOURS: "1"

job:
  env:
    LOG_LEVEL: DEBUG
  envFromConfigmaps:
    SH_DB_HOST: "common-signal-store.SH_DB_HOST"
    SH_DB_NAME: "common-signal-store.SH_DB_NAME"
    SH_DB_PORT: "common-signal-store.SH_DB_PORT"
    SH_DB_SCHEMA: "common-signal-store.SH_DB_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.SH_DB_USE_SSL"
  envFromSecrets:
    SH_DB_USERNAME: "signal-store-batch-cleanup-user.username"
    SH_DB_PASSWORD: "signal-store-batch-cleanup-user.password"
