name: "signalhub-be-push-signal"

roleArn: "arn:aws:iam::654654262692:role/signalhub-be-push-signal-uat"

service:
  create: true
  portName: http
  containerPort: 8088
  targetGroupArn: "arn:aws:elasticloadbalancing:eu-south-1:654654262692:targetgroup/uat-push-signal/ceae35ee8ddc0c0a"

configmap:
  ACCEPTED_AUDIENCE: "interop-signalhub-push-signal"
  QUEUE_URL: "https://sqs.eu-south-1.amazonaws.com/654654262692/signalhub-push-signal-uat"

deployment:
  env:
    HOST: "0.0.0.0"
    PORT: 8088
    SH_MAX_CONNECTION_POOL: "10"
  envFromConfigmaps:
    WELL_KNOWN_URLS: "common-jwt.WELL_KNOWN_URLS"
    SH_DB_HOST: "common-signal-store.DB_HOST_RO"
    SH_DB_NAME: "common-signal-store.DB_NAME"
    SH_DB_PORT: "common-signal-store.DB_PORT"
    SH_DB_SIGNALHUB_SCHEMA: "common-signal-store.DB_SIGNALHUB_SCHEMA"
    SH_DB_INTEROP_SCHEMA: "common-signal-store.DB_INTEROP_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.DB_USE_SSL"
  envFromSecrets:
    SH_DB_USERNAME: "signal-store-push-signal-user.username"
    SH_DB_PASSWORD: "signal-store-push-signal-user.password"
  livenessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
  readinessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
