PUSH_SIGNAL_IMAGE_VERSION="1.0.0"
PULL_SIGNAL_IMAGE_VERSION="1.0.0"
SIGNAL_PERSISTER_IMAGE_VERSION="1.0.0"
AGREEMENT_EVENT_CONSUMER_IMAGE_VERSION="1.0.0"
ESERVICE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0"
PURPOSE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0"
LOAD_TESTING_IMAGE_VERSION="1.0.0"

JOB_BATCH_CLEANUP_IMAGE_VERSION="1.0.0"
