name: "signalhub-be-signal-persister"

roleArn: "arn:aws:iam::654654262692:role/signalhub-be-signal-persister-uat"

configmap:
  QUEUE_URL: "https://sqs.eu-south-1.amazonaws.com/654654262692/signalhub-push-signal-uat"

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "common-flyway-migrations"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "uat"
      FLYWAY_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      FLYWAY_DEFAULT_SCHEMA: "uat_flyway"
      FLYWAY_SCHEMAS: "uat_flyway,uat_interop,uat_signalhub"
    envFromConfigmaps:
      POSTGRES_HOST: "common-signal-store.DB_HOST_RW"
      POSTGRES_PORT: "common-signal-store.DB_PORT"
      POSTGRES_DB: "common-signal-store.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "signal-store-flyway-user.username"
      FLYWAY_PASSWORD: "signal-store-flyway-user.password"

  envFromConfigmaps:
    SH_DB_HOST: "common-signal-store.DB_HOST_RW"
    SH_DB_NAME: "common-signal-store.DB_NAME"
    SH_DB_PORT: "common-signal-store.DB_PORT"
    SH_DB_SIGNALHUB_SCHEMA: "common-signal-store.DB_SIGNALHUB_SCHEMA"
    SH_DB_INTEROP_SCHEMA: "common-signal-store.DB_INTEROP_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.DB_USE_SSL"
  envFromSecrets:
    SH_DB_USERNAME: "signal-store-signal-persister-user.username"
    SH_DB_PASSWORD: "signal-store-signal-persister-user.password"
  livenessProbe:
  readinessProbe:
