namespace: "vapt"
techStack: "nodejs"

deployment:
  enableRolloutAnnotations: true
  replicas: 0 # enable only during VAPT sessions
  image:
    repositoryPrefix: "058264142001.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  env:
    LOG_LEVEL: "info"
