PUSH_SIGNAL_IMAGE_VERSION="develop"
PULL_SIGNAL_IMAGE_VERSION="develop"
SIGNAL_PERSISTER_IMAGE_VERSION="develop"
AGREEMENT_EVENT_CONSUMER_IMAGE_VERSION="develop"
ESERVICE_EVENT_CONSUMER_IMAGE_VERSION="develop"
PURPOSE_EVENT_CONSUMER_IMAGE_VERSION="develop"
LOAD_TESTING_IMAGE_VERSION="1.x-latest"

JOB_BATCH_CLEANUP_IMAGE_VERSION="develop"
