PUSH_SIGNAL_IMAGE_VERSION="1.0.0-RC4"
PULL_SIGNAL_IMAGE_VERSION="1.0.0-RC4"
SIGNAL_PERSISTER_IMAGE_VERSION="1.0.0-RC4"
AGREEMENT_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC4"
ESERVICE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC4"
PURPOSE_EVENT_CONSUMER_IMAGE_VERSION="1.0.0-RC4"
LOAD_TESTING_IMAGE_VERSION="1.x-latest"

JOB_BATCH_CLEANUP_IMAGE_VERSION="1.0.0-RC4"
