name: "signalhub-be-push-signal"

roleArn: "arn:aws:iam::058264553932:role/signalhub-be-push-signal-dev"

service:
  create: true
  portName: http
  containerPort: 8088
  targetGroupArn: "arn:aws:elasticloadbalancing:eu-south-1:058264553932:targetgroup/dev-push-signal/b6f1b1ff0095e4b9"

configmap:
  ACCEPTED_AUDIENCE: "interop-signalhub-push-signal"
  QUEUE_URL: "https://sqs.eu-south-1.amazonaws.com/058264553932/signalhub-push-signal-dev"

deployment:
  env:
    HOST: "0.0.0.0"
    PORT: 8088
  envFromConfigmaps:
    WELL_KNOWN_URLS: "common-jwt.WELL_KNOWN_URLS"
    SH_DB_HOST: "common-signal-store.SH_DB_HOST"
    SH_DB_NAME: "common-signal-store.SH_DB_NAME"
    SH_DB_PORT: "common-signal-store.SH_DB_PORT"
    SH_DB_SIGNALHUB_SCHEMA: "common-signal-store.SH_DB_SIGNALHUB_SCHEMA"
    SH_DB_INTEROP_SCHEMA: "common-signal-store.SH_DB_INTEROP_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.SH_DB_USE_SSL"
  envFromSecrets:
    SH_DB_USERNAME: "signal-store-push-signal-user.username"
    SH_DB_PASSWORD: "signal-store-push-signal-user.password"
  livenessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
  readinessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
