name: "signalhub-be-batch-update"

techStack: "nodejs"

roleArn: "arn:aws:iam::058264553932:role/signalhub-be-batch-update-dev"

schedule: "* * * * *"
suspend: true

deployment:
  env:
    APPLICATION_TYPE: ""
    ATTEMPT_EVENT: 0
    EVENTS_LIMIT: 50
  envFromConfigmaps:
    SH_DB_HOST: "common-signal-store.SH_DB_HOST"
    SH_DB_NAME: "common-signal-store.SH_DB_NAME"
    SH_DB_PORT: "common-signal-store.SH_DB_PORT"
    SH_DB_SCHEMA: "common-signal-store.SH_DB_SCHEMA"
    SH_DB_USE_SSL: "common-signal-store.SH_DB_USE_SSL"
  envFromSecrets:
    SH_DB_USERNAME: "signal-store-batch-update-user.username"
    SH_DB_PASSWORD: "signal-store-batch-update-user.password"


