name: DEV - PR Validation

#TODO cambiare condizione
on: 
  workflow_dispatch:
    inputs:
      skipDiff:
        description: 'Skip diff'
        required: true
        default: 'false'
        type: choice
        options:
        - true
        - false
      applyTestMode:
        description: 'Kubectl apply test mode on'
        required: true
        default: 'false'
        type: choice
        options:
        - true
        - false

#on:
#  pull_request:
#    types: [opened, edited, reopened]      

permissions:
  id-token: write
  contents: read

jobs:
  create_runner:
    name: Create Self-Hosted Runner
    runs-on: ubuntu-22.04
    environment: dev
    outputs:
      ecs_task_id: ${{ steps.start_runner.outputs.ecs_task_id }}
    strategy:
      matrix:
        index: [1,2,3]
      fail-fast: false
    steps:
      - name: Start GitHub Runner
        id: start_runner
        uses: pagopa/interop-github-runner-aws-create-action@main
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          iam_role_arn: ${{ secrets.ECS_IAM_ROLE_ARN }}
          ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
          ecs_task_definition: ${{ secrets.ECS_TASK_DEFINITION }}
          ecs_task_cpu: ${{ vars.ECS_TASK_CPU }}
          ecs_task_memory: ${{ vars.ECS_TASK_MEMORY }}
          ecs_container_name: ${{ vars.ECS_TASK_CONTAINER_NAME }}
          ecs_task_subnet_id: ${{ secrets.SUBNET_ID }}
          ecs_task_sec_group: ${{ secrets.SEC_GROUP_ID }}
          ecs_task_max_duration_seconds: ${{ vars.ECS_TASK_MAX_DURATION_SECONDS }}
          pat_token: ${{ secrets.BOT_TOKEN }}
          environment: dev
  
  lint:
    needs: [ create_runner ]
    secrets: inherit
    uses: ./.github/workflows/pr-validation-sub-core-validation.yaml
    with:
      environment: dev
  
  diff:
    needs: [ create_runner, lint ]
    secrets: inherit
    if: ${{ inputs.skipDiff == 'false' }}
    uses: ./.github/workflows/pr-validation-sub-core-diff.yaml
    with:
      environment: dev

  deploy:
    needs: [ create_runner, lint, diff ]
    secrets: inherit
    if: ${{ inputs.applyTestMode == 'true' }}
    uses: ./.github/workflows/pr-validation-sub-single-apply.yaml
    with:
      environment: dev
      timeout_seconds: 180
  

  delete_runner:
    name: Delete Self-Hosted Runner
    needs: [create_runner, lint, diff, deploy]
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    environment: dev
    strategy:
      matrix:
        index: [1,2,3]
      fail-fast: false
    steps:
      - name: Stop Github Runner
        id: stop_runner
        uses: pagopa/interop-github-runner-aws-cleanup-action@main
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          iam_role_arn: ${{ secrets.ECS_IAM_ROLE_ARN }}
          ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
          pat_token: ${{ secrets.BOT_TOKEN }}
          environment: dev
    
