name: Print Diff Summary (sub)

on: workflow_call

defaults:
  run:
    shell: bash

jobs:
  print_summary:
    name: Print Diff Summary
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Download diff artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
        with:
          path: ./diff-artifacts
          merge-multiple: true
      - name: Print summary
        run: |
          set -euo pipefail

          echo "### K8s Diff Summary" >> $GITHUB_STEP_SUMMARY
          
          if [ -d diff-artifacts ]; then

            # Initialize an associative array to store microservices for each environment
            declare -A microservices_by_env
            declare -A cronjobs_by_env

            microservices=$(ls -R ./diff-artifacts | { grep -i "microservices" || :; } |  tr "\n" ",")
            cronjobs=$(ls -R ./diff-artifacts | { grep -i "cronjobs" || :; } | tr "\n" ",")

            if [ -n "$microservices" ]; then
              IFS=',' read -r -a MICROSERVICES_WITH_DIFF <<< "$microservices"
              if [ -n "$MICROSERVICES_WITH_DIFF" ]; then
                for item in ${MICROSERVICES_WITH_DIFF[@]}; do
                  # Get the environment prefix (everything before '_microservice_' or '_cronjobs_')
                  environment="${item%%_microservices_*}"
                  
                  # Get the microservice name (everything after '_microservice_' and before '_diff.txt')
                  microservice_name="${item#*_microservices_}"
                  microservice_name="${microservice_name%_diff.txt}"

                  # Add the microservice to the corresponding environment list
                  if [[ -n ${microservices_by_env[$environment]+exists} ]]; then
                    # Append to existing environment's microservice list
                    microservices_by_env[$environment]+="${microservice_name},"
                  else
                    # Initialize new list for this environment
                    microservices_by_env[$environment]="${microservice_name},"
                  fi
                done                
              fi
            fi
            
            if [ -n "$cronjobs" ]; then
              IFS=',' read -r -a CRONJOBS_WITH_DIFF <<< "$cronjobs"
              if [ -n "$CRONJOBS_WITH_DIFF" ]; then
                for item in ${CRONJOBS_WITH_DIFF[@]}; do
                  # Get the environment prefix (everything before '_cronjobs_')
                  environment="${item%%_cronjobs_*}"
                  
                  # Get the cronjob name (everything after '_cronjobs_' and before '_diff.txt')
                  cronjob_name="${item#*_cronjobs_}"
                  cronjob_name="${cronjob_name%_diff.txt}"

                  # Add the cronjob to the corresponding environment list
                  if [[ -n ${cronjobs_by_env[$environment]+exists} ]]; then
                    # Append to existing environment's cronjob list
                    cronjobs_by_env[$environment]+="${cronjob_name},"
                  else
                    # Initialize new list for this environment
                    cronjobs_by_env[$environment]="${cronjob_name},"
                  fi                  
                done                
              fi
            fi

            # Output the results, grouped by environment
            for environment in "${!microservices_by_env[@]}"; do
              echo "### $environment:" >> $GITHUB_STEP_SUMMARY
              echo "#### Microservices:" >> $GITHUB_STEP_SUMMARY
              
              # Remove the trailing comma
              microservices_list=${microservices_by_env[$environment]%,}

              IFS=',' read -ra microservice_array <<< "$microservices_list"
              for microservice in "${microservice_array[@]}"; do
                echo "- $microservice" >> $GITHUB_STEP_SUMMARY
              done

              if [[ -n ${cronjobs_by_env[$environment]+exists} ]]; then
                echo "#### Cronjobs:" >> $GITHUB_STEP_SUMMARY
                
                cronjobs_list=${cronjobs_by_env[$environment]%,}
                IFS=',' read -ra cronjobs_array <<< "$cronjobs_list"
                for cronjob in "${cronjobs_array[@]}"; do
                  echo "- $cronjob" >> $GITHUB_STEP_SUMMARY
                done
              fi
            done

            # Output environments that have cronjobs but no microservices
            for environment in "${!cronjobs_by_env[@]}"; do
              if [[ -z ${microservices_by_env[$environment]+exists} ]]; then
                echo "### $environment:" >> $GITHUB_STEP_SUMMARY
                echo "#### Cronjobs:" >> $GITHUB_STEP_SUMMARY

                cronjobs_list=${cronjobs_by_env[$environment]%,}
                IFS=',' read -ra cronjobs_array <<< "$cronjobs_list"
                for cronjob in "${cronjobs_array[@]}"; do
                  echo "- $cronjob" >> $GITHUB_STEP_SUMMARY
                done
              fi
            done

          else
            echo "No diff found" >> $GITHUB_STEP_SUMMARY
          fi

